import type { BuilderDraft } from "@/lib/templates/builder";

type DraftWithPageExtras = BuilderDraft & {
  pageBackgroundImage?: string;
  pageBackgroundImageFit?: "clip" | "zoom" | "stretch";
  pageBlockAppearance?: Record<string, unknown>;
  pageLength?: string;
};

type DraftPage = DraftWithPageExtras & {
  id: string;
  slug: string;
  title: string;
  display_order: number;
};

type DraftWithPages = DraftWithPageExtras & {
  pages: DraftPage[];
};

const babyShowerPlayfulHomePage: DraftPage = {
  id: "home",
  slug: "home",
  title: "Baby Shower",
  display_order: 0,
  slugSuggestion: "baby_shower",
  subtitle: "Astird",
  subtext: "",
  description: "",
  pageBackground: "",
  blocks: [
    {
      id: "image_ok0mb5ut",
      type: "image",
      label: "Image",
      grid: { colStart: 1, rowStart: 1, colSpan: 12, rowSpan: 14, zIndex: 2 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        image: {
          id: "img_iirwjlpy",
          url: "https://koxykctwdpvmfwyzxgxt.supabase.co/storage/v1/object/public/uploads/1777224272054-hxw3v5fpbzr.webp",
          fitMode: "zoom",
          frame: "square",
          positionX: 50,
          positionY: 50,
          zoom: 1,
          rotation: 0,
          opacity: 1,
          fade: { top: false, bottom: true, left: false, right: false, size: 2 },
        },
      },
    },
    {
      id: "label_6mun0523",
      type: "label",
      label: "Label",
      grid: { colStart: 1, rowStart: 3.75, colSpan: 12, rowSpan: 1, zIndex: 4 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        text: "Join us for a",
        style: {
          fontFamily: "Georgia",
          fontSize: 60,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#769186",
        },
      },
    },
    {
      id: "label_pccp1e",
      type: "label",
      label: "Label",
      grid: { colStart: 1, rowStart: 5.75, colSpan: 12, rowSpan: 1, zIndex: 5 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        text: "honoring",
        style: {
          fontFamily: "Georgia",
          fontSize: 60,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#769186",
        },
      },
    },
    {
      id: "cta_lieiuqv2",
      type: "cta",
      label: "Button",
      grid: { colStart: 3, rowStart: 8.25, colSpan: 3.5, rowSpan: 1.25, zIndex: 7 },
      appearance: {
        backgroundColor: "#fdd487",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 66,
      },
      data: {
        heading: "",
        body: "",
        buttonText: "       I will be there       ",
        buttonUrl: "/s/preset/baby_shower/playful/rsvp-accept",
        style: {
          fontFamily: "Inter",
          fontSize: 44,
          bold: true,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#ffffff",
        },
        styleType: "solid",
      },
    },
    {
      id: "cta_zzs1qv",
      type: "cta",
      label: "Button",
      grid: { colStart: 7.5, rowStart: 8.25, colSpan: 3.5, rowSpan: 1.25, zIndex: 8 },
      appearance: {
        backgroundColor: "#94cef3",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 66,
      },
      data: {
        heading: "",
        body: "",
        buttonText: "  Sorry, can't make it  ",
        buttonUrl: "/s/preset/baby_shower/playful/rsvp-decline",
        style: {
          fontFamily: "Inter",
          fontSize: 44,
          bold: true,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#ffffff",
        },
        styleType: "solid",
      },
    },
    {
      id: "label_ldp09ga1",
      type: "label",
      label: "Label",
      grid: { colStart: 1, rowStart: 10, colSpan: 12, rowSpan: 1.75, zIndex: 9 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        text: "DATE • TIME\nVENUE NAME\nADDRESS",
        style: {
          fontFamily: "inherit",
          fontSize: 40,
          bold: true,
          italic: true,
          underline: false,
          strike: false,
          align: "center",
          color: "#97b8ba",
        },
      },
    },
  ],
  pageElements: {
    title: { colStart: 1, rowStart: 4.25, colSpan: 12, rowSpan: 2.5, zIndex: 3 },
    subtitle: { colStart: 1, rowStart: 6, colSpan: 12, rowSpan: 2.25, zIndex: 6 },
    subtext: { colStart: 2, rowStart: 4, colSpan: 6, rowSpan: 1, zIndex: 3 },
    description: { colStart: 2, rowStart: 5, colSpan: 8, rowSpan: 2, zIndex: 4 },
  },
  pageVisibility: {
    title: true,
    subtitle: true,
  },
  titleStyle: {
    fontFamily: "Pacifico",
    fontSize: 160,
    bold: false,
    italic: false,
    underline: false,
    strike: false,
    align: "center",
    color: "#5f8cca",
  },
  subtitleStyle: {
    fontFamily: "Pacifico",
    fontSize: 190,
    bold: false,
    italic: false,
    underline: false,
    strike: false,
    align: "center",
    color: "#fba19f",
  },
};

const babyShowerPlayfulRsvpAcceptPage: DraftPage = {
  id: "page-rsvp-accept",
  slug: "rsvp-accept",
  title: "RSVP Accept",
  display_order: 1,
  slugSuggestion: "baby_shower",
  subtitle: "",
  subtext: "",
  description: "",
  pageBackground: "",
  blocks: [
    {
      id: "image_ok0mb5ut_accept",
      type: "image",
      label: "Image",
      grid: { colStart: 1, rowStart: 1, colSpan: 12, rowSpan: 14, zIndex: 2 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        image: {
          id: "img_iirwjlpy_accept",
          url: "/designs/backgrounds/design_baby_shower_playful_scenery.png",
          fitMode: "zoom",
          frame: "square",
          positionX: 50,
          positionY: 50,
          zoom: 1,
          rotation: 0,
          opacity: 1,
          fade: { top: false, bottom: true, left: false, right: false, size: 2 },
          alt: "design_baby_shower_playful_scenery.png",
        },
      },
    },
    {
      id: "rsvp_qz5jv4l7_accept",
      type: "rsvp",
      label: "RSVP",
      grid: { colStart: 1, rowStart: 2.25, colSpan: 12, rowSpan: 7.25, zIndex: 3 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        heading: "Baby Shower RSVP",
        imageUrl: "",
        imageFrameShape: "circle",
        elementOrder: [
          "image",
          "heading",
          "nameLabel",
          "firstName",
          "lastName",
          "email",
          "address",
          "attending",
          "meal",
          "guestToggle",
          "guestCount",
          "guestName",
          "comments",
        ],
        hiddenElements: [],
        guestMin: 0,
        guestMax: 1,
        attendingLabel: "Are you attending?",
        attendingOptions: ["Yes", "No"],
        attendingDisplay: true,
        attendingDefaultValue: "Yes",
        mealLabel: "Your meal selection:",
        mealOptions: ["Option 1", "Option 2"],
        mealDisplay: false,
        mealDefaultValue: "Option 1",
        guestLabel: "Are you bringing a guest?",
        guestOptions: ["Yes", "No"],
        guestDisplay: false,
        guestDefaultValue: "No",
        commentsLabel: "Additional comments",
        commentsPlaceholder: "Additional comments",
        commentsDisplay: true,
        commentsDefaultValue: "",
        submitButtonText: "Submit RSVP",
        elementStyles: {
          heading: {
            textStyle: {
              fontFamily: "Pacifico",
              color: "#000000",
              align: "center",
              fontSize: 49,
            },
          },
        },
        style: {
          fontFamily: "inherit",
          fontSize: 16,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "left",
          color: "#111827",
        },
      },
    },
  ],
  pageElements: {
    title: { colStart: 1, rowStart: 4.25, colSpan: 12, rowSpan: 2.5, zIndex: 3 },
    subtitle: { colStart: 1, rowStart: 6, colSpan: 12, rowSpan: 2.25, zIndex: 6 },
    subtext: { colStart: 2, rowStart: 4, colSpan: 6, rowSpan: 1, zIndex: 3 },
    description: { colStart: 2, rowStart: 5, colSpan: 8, rowSpan: 2, zIndex: 4 },
  },
  pageVisibility: {
    title: false,
    subtitle: false,
  },
};

const babyShowerPlayfulRsvpDeclinePage: DraftPage = {
  id: "page-rsvp-decline",
  slug: "rsvp-decline",
  title: "RSVP Decline",
  display_order: 2,
  slugSuggestion: "baby_shower",
  subtitle: "",
  subtext: "",
  description: "",
  pageBackground: "",
  blocks: [
    {
      id: "image_ok0mb5ut_decline",
      type: "image",
      label: "Image",
      grid: { colStart: 1, rowStart: 1, colSpan: 12, rowSpan: 14, zIndex: 2 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        image: {
          id: "img_iirwjlpy_decline",
          url: "/designs/backgrounds/design_baby_shower_dark_scenery.png",
          fitMode: "zoom",
          frame: "square",
          positionX: 50,
          positionY: 50,
          zoom: 1,
          rotation: 0,
          opacity: 1,
          fade: { top: false, bottom: true, left: false, right: false, size: 2 },
          alt: "design_baby_shower_dark_scenery.png",
        },
      },
    },
    {
      id: "rsvp_qz5jv4l7_decline",
      type: "rsvp",
      label: "RSVP",
      grid: { colStart: 1, rowStart: 2.25, colSpan: 12, rowSpan: 7.25, zIndex: 3 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        heading: "Sorry You Can't Make It",
        imageUrl: "",
        imageFrameShape: "circle",
        elementOrder: [
          "image",
          "heading",
          "nameLabel",
          "firstName",
          "lastName",
          "email",
          "address",
          "attending",
          "meal",
          "guestToggle",
          "guestCount",
          "guestName",
          "comments",
        ],
        hiddenElements: [],
        guestMin: 0,
        guestMax: 1,
        attendingLabel: "Are you attending?",
        attendingOptions: ["Yes", "No"],
        attendingDisplay: false,
        attendingDefaultValue: "No",
        mealLabel: "Your meal selection:",
        mealOptions: ["Option 1", "Option 2"],
        mealDisplay: false,
        mealDefaultValue: "Option 1",
        guestLabel: "Are you bringing a guest?",
        guestOptions: ["Yes", "No"],
        guestDisplay: false,
        guestDefaultValue: "No",
        commentsLabel: "Additional comments",
        commentsPlaceholder: "Leave a note for the host",
        commentsDisplay: true,
        commentsDefaultValue: "",
        submitButtonText: "Submit RSVP",
        elementStyles: {
          heading: {
            textStyle: {
              fontFamily: "Permanent Marker",
              color: "#ffffff",
              align: "center",
              fontSize: 43,
            },
          },
          nameLabel: { textStyle: { color: "#ffffff" } },
          attending: { textStyle: { color: "#ffffff" } },
          comments: { textStyle: { color: "#ffffff" } },
        },
        style: {
          fontFamily: "inherit",
          fontSize: 16,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "left",
          color: "#111827",
        },
      },
    },
  ],
  pageElements: {
    title: { colStart: 1, rowStart: 4.25, colSpan: 12, rowSpan: 2.5, zIndex: 3 },
    subtitle: { colStart: 1, rowStart: 6, colSpan: 12, rowSpan: 2.25, zIndex: 6 },
    subtext: { colStart: 2, rowStart: 4, colSpan: 6, rowSpan: 1, zIndex: 3 },
    description: { colStart: 2, rowStart: 5, colSpan: 8, rowSpan: 2, zIndex: 4 },
  },
  pageVisibility: {
    title: false,
    subtitle: false,
  },
};

const babyShowerPlayfulDraft: DraftWithPages = {
  ...babyShowerPlayfulHomePage,
  pages: [
    babyShowerPlayfulHomePage,
    babyShowerPlayfulRsvpAcceptPage,
    babyShowerPlayfulRsvpDeclinePage,
  ],
};

export default babyShowerPlayfulDraft;