// drafts/wedding/modern.draft.ts

import type { BuilderDraft } from "@/lib/templates/builder";

type DraftWithPageExtras = BuilderDraft & {
  pageColor?: string;
  pageBackgroundImage?: string;
  pageBackgroundImageFit?: "clip" | "zoom" | "stretch";
  pageBlockAppearance?: Record<string, unknown>;
  pageLength?: string;
};

type DraftPage = DraftWithPageExtras & {
  id: string;
  slug: string;
  title: string;
  display_order: number;
};

type DraftWithPages = DraftWithPageExtras & {
  pages: DraftPage[];
};

const homePage: DraftPage = {
  id: "home",
  slug: "home",
  title: "",
  display_order: 0,
  subtitle: "",
  subtext: "",
  description: "",
  countdownLabel: "",

  titleStyle: {
    fontFamily: "Great Vibes",
    fontSize: 200,
    align: "center",
    bold: false,
    color: "#646462",
  },

  subtitleStyle: {
    fontFamily: "Cormorant Garamond",
    fontSize: 60,
    align: "center",
    color: "#374151",
  },

  subtextStyle: {
    fontFamily: "Cormorant Garamond",
    fontSize: 106,
    italic: true,
    bold: true,
    align: "center",
    color: "#374151",
  },

  descriptionStyle: {
    fontFamily: "Great Vibes",
    fontSize: 110,
    align: "center",
    color: "#646462",
  },

  countdownLabelStyle: {
    fontFamily: "Great Vibes",
    fontSize: 94,
    align: "center",
    color: "#000000",
  },

  slugSuggestion: "ourwedding",
  pageBackground: "#ffffff",
  pageBackgroundImage: "",
  pageBackgroundImageFit: "zoom",
  pageScale: 85,

  pageVisibility: {
    title: false,
    subtitle: false,
    subtext: false,
    description: false,
  },

  pageElements: {
    title: {
      colStart: 2,
      rowStart: 1,
      colSpan: 8,
      rowSpan: 2,
      zIndex: 1,
    },
    subtitle: {
      colStart: 2,
      rowStart: 3,
      colSpan: 7,
      rowSpan: 1,
      zIndex: 2,
    },
    subtext: {
      colStart: 2,
      rowStart: 4,
      colSpan: 6,
      rowSpan: 1,
      zIndex: 3,
    },
    description: {
      colStart: 2,
      rowStart: 5,
      colSpan: 8,
      rowSpan: 2,
      zIndex: 4,
    },
  },

  blocks: [
    {
      id: "modern-couple-image",
      type: "image",
      label: "Couple Image",
      grid: {
        colStart: 5,
        rowStart: 3,
        colSpan: 4,
        rowSpan: 9,
        zIndex: 26,
      },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 0,
      },
      data: {
        image: {
          id: "modern-couple-image-src",
          url: "/designs/artifacts/bride_groom1.png",
          alt: "Bride and groom",
          fitMode: "stretch",
          frame: "square",
          positionX: 50,
          positionY: 50,
          zoom: 1,
          rotation: 0,
        },
      },
    },

    {
      id: "links_jym5qwlb",
      type: "links",
      label: "Navigation Link",
      grid: {
        colStart: 1,
        rowStart: 1,
        colSpan: 2.5,
        rowSpan: 1.25,
        zIndex: 28,
      },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        heading: "",
        items: [{ id: "link-about", label: "ABOUT", url: "https://ourwedding.ko-host.com/about" }],
        style: {
          fontFamily: "Playfair Display",
          fontSize: 60,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#111827",
        },
        backgroundColor: "#ffffff",
        transparentBackground: true,
      },
    },

    {
      id: "links_4ue9rf",
      type: "links",
      label: "Navigation Link",
      grid: {
        colStart: 4,
        rowStart: 1,
        colSpan: 2.5,
        rowSpan: 1.25,
        zIndex: 18,
      },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        heading: "",
        items: [{ id: "link-registry", label: "REGISTRY", url: "https://ourwedding.ko-host.com/registry" }],
        style: {
          fontFamily: "Playfair Display",
          fontSize: 60,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#111827",
        },
        backgroundColor: "#ffffff",
        transparentBackground: true,
      },
    },

    {
      id: "links_0pa6r7",
      type: "links",
      label: "Navigation Link",
      grid: {
        colStart: 7.25,
        rowStart: 1,
        colSpan: 2.5,
        rowSpan: 1.25,
        zIndex: 19,
      },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        heading: "",
        items: [{ id: "link-schedule", label: "SCHEDULE", url: "https://ourwedding.ko-host.com/schedule" }],
        style: {
          fontFamily: "Playfair Display",
          fontSize: 60,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#111827",
        },
        backgroundColor: "#ffffff",
        transparentBackground: true,
      },
    },

    {
      id: "links_1oqmxz",
      type: "links",
      label: "Navigation Link",
      grid: {
        colStart: 10,
        rowStart: 1,
        colSpan: 2.5,
        rowSpan: 1.25,
        zIndex: 20,
      },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        heading: "",
        items: [{ id: "link-contact", label: "CONTACT", url: "https://ourwedding.ko-host.com/contact" }],
        style: {
          fontFamily: "Playfair Display",
          fontSize: 60,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#111827",
        },
        backgroundColor: "#ffffff",
        transparentBackground: true,
      },
    },

    {
      id: "label_bvoi5m1j",
      type: "label",
      label: "Label",
      grid: {
        colStart: 1,
        rowStart: 9.75,
        colSpan: 12,
        rowSpan: 2.25,
        zIndex: 50,
      },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        text: "JOIN US AS WE BEGIN\nOUR GREATEST ADVENTURE",
        style: {
          fontFamily: "Cormorant Garamond",
          fontSize: 84,
          bold: false,
          italic: true,
          underline: false,
          strike: false,
          align: "center",
          color: "#7d8068",
        },
      },
    },

    {
      id: "label_abi2evyq",
      type: "label",
      label: "Label",
      grid: {
        colStart: 1,
        rowStart: 12,
        colSpan: 12,
        rowSpan: 1,
        zIndex: 49,
      },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        text: "Two hearts, one day, a lifetime to follow",
        style: {
          fontFamily: "Dancing Script",
          fontSize: 54,
          bold: false,
          italic: true,
          underline: false,
          strike: false,
          align: "center",
          color: "#111827",
        },
      },
    },

    {
      id: "image_pe7sieim",
      type: "image",
      label: "Image",
      grid: {
        colStart: 1,
        rowStart: 9.5,
        colSpan: 12,
        rowSpan: 3.75,
        zIndex: 45,
      },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#050505",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        image: {
          id: "img_1e4nkk2s",
          url: "/designs/artifacts/shape_semi_circle.png",
          fitMode: "stretch",
          frame: "square",
          positionX: 50,
          positionY: 65,
          zoom: 1.17,
          rotation: 0,
          opacity: 1,
          fade: {
            top: true,
            bottom: true,
            left: true,
            right: true,
            size: 29,
          },
          alt: "shape_semi_circle.png",
        },
      },
    },

    {
      id: "shape_6odsnupz",
      type: "shape",
      label: "Shape",
      grid: {
        colStart: 1,
        rowStart: 11.5,
        colSpan: 12,
        rowSpan: 9.5,
        zIndex: 48,
      },
      appearance: {
        backgroundColor: "#ffffff",
        borderColor: "#f7f3ef",
        borderWidth: 1,
        borderRadius: 16,
      },
      data: {
        shapeType: "rectangle",
        fade: {
          top: true,
          size: 19,
        },
      },
    },

    {
      id: "image_761indgj",
      type: "image",
      label: "Image",
      grid: {
        colStart: 1,
        rowStart: 1,
        colSpan: 12,
        rowSpan: 12,
        zIndex: 17,
      },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        image: {
          id: "img_cpln3jw4",
          url: "https://koxykctwdpvmfwyzxgxt.supabase.co/storage/v1/object/public/uploads/1777136179844-80ap6k7oro.webp",
          fitMode: "zoom",
          frame: "square",
          positionX: 50,
          positionY: 50,
          zoom: 1,
          rotation: 0,
          opacity: 1,
          fade: {
            top: false,
            bottom: false,
            left: false,
            right: false,
            size: 15,
          },
        },
      },
    },

    {
      id: "label_fe9comiw",
      type: "label",
      label: "Label",
      grid: {
        colStart: 1,
        rowStart: 19.5,
        colSpan: 12,
        rowSpan: 2.5,
        zIndex: 51,
      },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        text: "Catherine & Bartholomew",
        style: {
          fontFamily: "Parisienne",
          fontSize: 150,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#d8c2ab",
        },
      },
    },

    {
      id: "rsvp_jiu1q53d",
      type: "rsvp",
      label: "RSVP",
      grid: {
        colStart: 3.5,
        rowStart: 13.25,
        colSpan: 7.25,
        rowSpan: 6.5,
        zIndex: 52,
      },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        heading: "Cat & Bart Invitation RSVP Form",
        imageUrl: "",
        imageFrameShape: "circle",
        elementOrder: [
          "image",
          "heading",
          "nameLabel",
          "firstName",
          "lastName",
          "email",
          "address",
          "attending",
          "meal",
          "guestToggle",
          "guestCount",
          "guestName",
          "comments",
        ],
        hiddenElements: [],
        guestMin: 0,
        guestMax: 1,
        attendingLabel: "Are you attending?",
        attendingOptions: ["Yes", "No"],
        attendingDisplay: true,
        attendingDefaultValue: "Yes",
        mealLabel: "Your meal selection:",
        mealOptions: ["Chicken", "Salmon"],
        mealDisplay: true,
        mealDefaultValue: "Chicken",
        guestLabel: "Are you bringing a guest?",
        guestOptions: ["Yes", "No"],
        guestDisplay: true,
        guestDefaultValue: "No",
        commentsLabel: "Additional comments",
        commentsPlaceholder: "Additional comments",
        commentsDisplay: true,
        commentsDefaultValue: "",
        submitButtonText: "Submit RSVP",
        elementStyles: {},
        style: {
          fontFamily: "inherit",
          fontSize: 16,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "left",
          color: "#111827",
        },
      },
    },
  ],
};

const aboutPage: DraftPage = {
  id: "page-about",
  slug: "about",
  title: "about",
  display_order: 1,
  subtitle: "",
  subtext: "",
  description: "",
  slugSuggestion: "ourwedding",
  blocks: [
    {
      id: "label_9oz6ljs5",
      type: "label",
      label: "Label",
      grid: { colStart: 1, rowStart: 3.5, colSpan: 12, rowSpan: 1, zIndex: 2 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        text: "We invite you to join us as we celebrate our marriage...",
        style: {
          fontFamily: "Cormorant Garamond",
          fontSize: 62,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#111827",
        },
      },
    },
    {
      id: "label_zjj8pu",
      type: "label",
      label: "Label",
      grid: { colStart: 1, rowStart: 1.5, colSpan: 12, rowSpan: 1, zIndex: 3 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        text: "We’re saying “I do” under the open sky.",
        style: {
          fontFamily: "Playfair Display",
          fontSize: 48,
          bold: true,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#111827",
        },
      },
    },
    {
      id: "label_9t4nrd",
      type: "label",
      label: "Label",
      grid: { colStart: 1, rowStart: 2.5, colSpan: 12, rowSpan: 1, zIndex: 4 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        text: "Surrounded by nature and the people who mean everything to us, this outdoor\ncelebration is designed to feel effortless, meaningful, and unforgettable.",
        style: {
          fontFamily: "Satisfy",
          fontSize: 27,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#111827",
        },
      },
    },
    {
      id: "richtext_22sf79ej",
      type: "rich_text",
      label: "Rich Text",
      grid: { colStart: 2.75, rowStart: 4.5, colSpan: 4.25, rowSpan: 2.75, zIndex: 5 },
      appearance: {
        backgroundColor: "#f1f1f1",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        title: "",
        content:
          "<div><b>Ceremony</b></div><div><br></div>Willow Creek Gardens\n2458 Meadow Lane\nCharlottesville, VA 22903",
        style: {
          fontFamily: "Cormorant Garamond",
          fontSize: 37,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#111827",
        },
        listType: "none",
        linkUrl: "",
      },
    },
    {
      id: "rich_text_fqmyzs",
      type: "rich_text",
      label: "Rich Text",
      grid: { colStart: 7, rowStart: 4.5, colSpan: 4.25, rowSpan: 2.75, zIndex: 6 },
      appearance: {
        backgroundColor: "#f1f1f1",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        title: "",
        content:
          "<div><b>Reception</b></div><div><br></div>The Glasshouse at Riverview\r<div>1021 Riverbend Drive\r</div><div>Charlottesville, VA 22902</div>",
        style: {
          fontFamily: "Cormorant Garamond",
          fontSize: 37,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#000000",
        },
        listType: "none",
        linkUrl: "",
      },
    },
    {
      id: "label_tl5ae0",
      type: "label",
      label: "Label",
      grid: { colStart: 1, rowStart: 10.25, colSpan: 12, rowSpan: 1.25, zIndex: 3 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        text: "Our outdoor ceremony will reflect the natural beauty of the setting,\nfollowed by an evening of celebration just a short distance away.",
        style: {
          fontFamily: "Cormorant Garamond",
          fontSize: 39,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#f4f5f5",
        },
      },
    },
    {
      id: "map_v7e72wg5",
      type: "map_location",
      label: "Map / Location",
      grid: { colStart: 2.75, rowStart: 7, colSpan: 4.25, rowSpan: 3.25, zIndex: 7 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        heading: "Ceremony",
        locationName: "Willow Creek Gardens",
        address: "Willow Creek Gardens 2458 Meadow Lane Charlottesville, VA 22903",
        mapUrl:
          "https://www.google.com/maps/search/Willow+Creek+Gardens+2458+Meadow+Lane+Charlottesville+VA+22903/@38.0307857,-78.5618591,10z?entry=s&sa=X&ved=1t%3A199789",
        style: {
          fontFamily: "inherit",
          fontSize: 16,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "left",
          color: "#ffffff",
        },
      },
    },
    {
      id: "map_location_dqg4as",
      type: "map_location",
      label: "Map / Location",
      grid: { colStart: 7, rowStart: 7, colSpan: 4.25, rowSpan: 3.25, zIndex: 8 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        heading: "Reception",
        locationName: "The Glasshouse at Riverview",
        address: "The Glasshouse at Riverview 1021 Riverbend Drive Charlottesville, VA 22902",
        mapUrl:
          "https://www.google.com/maps/search/The+Glasshouse+at+Riverview+1021+Riverbend+Drive+Charlottesville,+VA+22902/@38.0306681,-78.4594888,17z/data=!3m1!4b1?entry=ttu&g_ep=EgoyMDI2MDQyMi4wIKXMDSoASAFQAw%3D%3D",
        style: {
          fontFamily: "inherit",
          fontSize: 16,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "left",
          color: "#ffffff",
        },
      },
    },
  ],
  pageColor: "#ffffff",
  pageBackground: "#ffffff",
  pageBackgroundImage: "/designs/backgrounds/design_wedding_modern_scenery.webp",
  pageBackgroundImageFit: "zoom",
  pageScale: 85,
  pageVisibility: { title: false, subtitle: false, subtext: false, description: false },
  pageElements: homePage.pageElements,
  pageBlockAppearance: {},
  pageLength: "1200",
};

const registryPage: DraftPage = {
  id: "page-registry",
  slug: "registry",
  title: "registry",
  display_order: 2,
  subtitle: "",
  subtext: "",
  description: "",
  slugSuggestion: "ourwedding",
  blocks: [
    {
      id: "label_8ywhsvsb",
      type: "label",
      label: "Label",
      grid: { colStart: 1, rowStart: 1.25, colSpan: 12, rowSpan: 2.5, zIndex: 2 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        text:
          "We’re so grateful to celebrate this special day with you.\nFor those who have asked, we’ve put together\na small registry to help us begin this next chapter.",
        style: {
          fontFamily: "Anton",
          fontSize: 51,
          bold: true,
          italic: false,
          underline: false,
          strike: false,
          align: "center",
          color: "#3e4f75",
        },
      },
    },
    {
      id: "registry_kbnwjvek",
      type: "registry",
      label: "Registry",
      grid: { colStart: 4, rowStart: 3.75, colSpan: 6.5, rowSpan: 12.25, zIndex: 3 },
      appearance: {
        backgroundColor: "#3e4f75",
        borderColor: "#3e4f75",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        heading: "Gift Registry",
        description: "Share gift ideas and registry links.",
        items: [
          {
            id: "registryitem_aa20vkxv",
            label: "Coffee Maker",
            url: "https://www.amazon.com/",
            store: "Amazon",
            price: "$10",
            note: "",
            imageUrl: "",
            quantity: 1,
            purchased: 0,
            contributors: [],
          },
          {
            id: "registryitem_n3rn4lqo",
            label: "Dinner Set",
            url: "https://www.amazon.com/",
            store: "Amazon",
            price: "$48.59",
            note: "",
            imageUrl: "",
            quantity: 1,
            purchased: 0,
            contributors: [],
          },
          {
            id: "registryitem_9d6my2es",
            label: "Queen Size Bed Set",
            url: "https://www.target.com/p/waffle-textured-comforter-set-all-season-down-alternative-ultra-soft-bedding-becky-cameron/-/A-90848106?preselect=90848124#lnk=sametab",
            store: "Target",
            price: "$69.78",
            note: "",
            imageUrl: "",
          },
          {
            id: "registryitem_axz734p6",
            label: "Slow Cooker",
            url: "https://www.jcpenney.com/p/laura-ashley-3-1-2-qt-slow-cooker/ppr5008686109?pTmplType=regular&geoZip=22401",
            store: "JCPenney",
            price: "$71.99",
            note: "",
            imageUrl: "http://jcpenney.scene7.com/is/image/JCPenney/DP0304202607072109M",
          },
        ],
        style: {
          fontFamily: "Anton",
          fontSize: 17,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "left",
          color: "#6e7b98",
        },
      },
    },
  ],
  pageColor: "#ffffff",
  pageBackground: "#ffffff",
  pageBackgroundImage: "/designs/backgrounds/design_wedding_modern_scenery.webp",
  pageBackgroundImageFit: "zoom",
  pageScale: 85,
  pageVisibility: { title: false, subtitle: false, subtext: false, description: false },
  pageElements: homePage.pageElements,
  pageBlockAppearance: {},
  pageLength: "3200",
};

const schedulePage: DraftPage = {
  id: "page-schedule",
  slug: "schedule",
  title: "schedule",
  display_order: 3,
  subtitle: "",
  subtext: "",
  description: "",
  slugSuggestion: "ourwedding",
  blocks: [
    {
      id: "richtext_y0be6yyy",
      type: "rich_text",
      label: "Rich Text",
      grid: { colStart: 2.5, rowStart: 9.75, colSpan: 9.25, rowSpan: 4.25, zIndex: 2 },
      appearance: {
        backgroundColor: "#ededed",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        title: "",
        content:
          '<!--StartFragment--><h2 data-section-id="1nrjwyc" data-start="1363" data-end="1387"><b>🚗 Additional Details</b></h2><div><br></div>\n<p data-start="1389" data-end="1487"><strong data-start="1389" data-end="1401">Parking:</strong><br data-start="1401" data-end="1404">\nOn-site parking is available near the venue. Attendants will be there to guide you.</p>\n<p data-start="1489" data-end="1579"><strong data-start="1489" data-end="1500">Attire:</strong><br data-start="1500" data-end="1503">\nSemi-formal / garden attire recommended. Please plan for an outdoor setting.</p>\n<p data-start="1581" data-end="1693"><strong data-start="1581" data-end="1598">Weather Note:</strong><br data-start="1598" data-end="1601">\nIn the event of inclement weather, the ceremony will be moved to a covered location on-site.</p><!--EndFragment-->',
        style: {
          fontFamily: "Poppins",
          fontSize: 25,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "left",
          color: "#111827",
        },
        listType: "none",
        linkUrl: "",
      },
    },
    {
      id: "agenda_mbh45f5v",
      type: "schedule_agenda",
      label: "Schedule / Agenda",
      grid: { colStart: 2.5, rowStart: 1.25, colSpan: 9.25, rowSpan: 6, zIndex: 3 },
      appearance: {
        backgroundColor: "transparent",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        heading: "Schedule",
        items: [
          {
            id: "agendaitem_ndjh707i",
            time: "4:30 PM",
            title: "🌿 Ceremony",
            description:
              "Please arrive by 4:00 PM to allow time for seating.\nOur ceremony will take place outdoors, so we recommend comfortable footwear and weather-appropriate attire.",
          },
          {
            id: "agendaitem_a0ixjgtx",
            time: "5:00 PM",
            title: "🥂 Cocktail Hour",
            description:
              "Lawn & Terrace\nImmediately following the ceremony, join us for cocktails, light bites, and conversation while we take photos.",
          },
          {
            id: "schedule_vdrhpc65",
            time: "6:00 PM",
            title: "🍽️ Reception",
            description:
              "The evening continues with dinner, toasts, and celebration.\nDinner service will begin shortly after guests are seated.",
          },
          {
            id: "schedule_kea3eb1y",
            time: "7:30 PM",
            title: "💃 Dancing & Celebration",
            description: "After dinner, the dance floor opens!\nJoin us as we celebrate into the evening.",
          },
          {
            id: "schedule_2mlpd396",
            time: "8:30 PM",
            title: "🍰 Cake Cutting",
            description:
              "We’ll be cutting the cake and would love for you to gather around and share in the moment.",
          },
          {
            id: "schedule_vweyyg6k",
            time: "10:30 PM",
            title: "🌙 Send-Off",
            description:
              "Help us end the night with a special send-off as we begin our next chapter together.",
          },
        ],
        style: {
          fontFamily: "Poppins",
          fontSize: 25,
          bold: true,
          italic: false,
          underline: false,
          strike: false,
          align: "left",
          color: "#111827",
        },
      },
    },
  ],
  pageColor: "#ffffff",
  pageBackground: "#ffffff",
  pageBackgroundImage: "/designs/backgrounds/design_wedding_modern_scenery.webp",
  pageBackgroundImageFit: "zoom",
  pageScale: 85,
  pageVisibility: { title: false, subtitle: false, subtext: false, description: false },
  pageElements: homePage.pageElements,
  pageBlockAppearance: {},
  pageLength: "1800",
};

const contactPage: DraftPage = {
  id: "page-contact",
  slug: "contact",
  title: "contact",
  display_order: 4,
  subtitle: "",
  subtext: "",
  description: "",
  slugSuggestion: "ourwedding",
  blocks: [
    {
      id: "richtext_llbjm4ba",
      type: "rich_text",
      label: "Rich Text",
      grid: { colStart: 2.5, rowStart: 1.25, colSpan: 9, rowSpan: 11.25, zIndex: 1 },
      appearance: {
        backgroundColor: "#fbf4f4",
        borderColor: "#D1D5DB",
        borderWidth: 0,
        borderRadius: 16,
      },
      data: {
        title: "",
        content:
          '<!--StartFragment--><h2 data-section-id="168ulpi" data-start="157" data-end="183">📞 Contact &amp; Assistance</h2>\n<p data-start="185" data-end="344">We want your experience to be as smooth and enjoyable as possible. If you have any questions leading up to the wedding day, please don’t hesitate to reach out.</p>\n<hr data-start="346" data-end="349">\n<h3 data-section-id="1a4dtdi" data-start="351" data-end="378">👰 Wedding Coordination</h3>\n<p data-start="380" data-end="442">For general questions about the schedule, venue, or logistics:</p>\n<p data-start="444" data-end="536"><strong data-start="444" data-end="467">Wedding Coordinator</strong><br data-start="467" data-end="470">\nEmily Carter<br data-start="482" data-end="485">\n📧 emily@evergreen-events.com<br data-start="514" data-end="517">\n📱 (555) 214-8893</p>\n<hr data-start="538" data-end="541">\n<h3 data-section-id="53ci6v" data-start="543" data-end="564">💌 Couple Contact</h3>\n<p data-start="566" data-end="642">For personal messages or anything else you’d like to share with us directly:</p>\n<p data-start="644" data-end="690"><strong data-start="644" data-end="660">Catherine &amp; Bartholomew</strong><br data-start="660" data-end="663">\n📧 catandbart@gmail.com</p>\n<hr data-start="692" data-end="695">\n<h3 data-section-id="6654hz" data-start="697" data-end="727">🏨 Travel &amp; Accommodations</h3>\n<p data-start="729" data-end="800">For help with hotel bookings, transportation, or local recommendations:</p>\n<p data-start="802" data-end="855"><strong data-start="802" data-end="820">Guest Services</strong><br data-start="820" data-end="823">\n📧 travel@evergreen-events.com</p>\n<hr data-start="857" data-end="860">\n<h3 data-section-id="jgg0uq" data-start="862" data-end="886">🚗 Day-Of Assistance</h3>\n<p data-start="888" data-end="974">If you need help on the day of the wedding (directions, timing, etc.), please contact:</p>\n<p data-start="976" data-end="1031"><strong data-start="976" data-end="994">Day-Of Contact</strong><br data-start="994" data-end="997">\nMichael Reed<br data-start="1009" data-end="1012">\n📱 (555) 872-4410</p><!--EndFragment-->',
        style: {
          fontFamily: "Playball",
          fontSize: 20,
          bold: false,
          italic: false,
          underline: false,
          strike: false,
          align: "left",
          color: "#111827",
        },
        listType: "none",
        linkUrl: "",
      },
    },
  ],
  pageColor: "#ffffff",
  pageBackground: "#ffffff",
  pageBackgroundImage: "/designs/backgrounds/design_wedding_modern_scenery.webp",
  pageBackgroundImageFit: "zoom",
  pageScale: 85,
  pageVisibility: { title: false, subtitle: false, subtext: false, description: false },
  pageElements: homePage.pageElements,
  pageBlockAppearance: {},
  pageLength: "1800",
};

const weddingModernDraft: DraftWithPages = {
  ...homePage,
  pages: [homePage, aboutPage, registryPage, schedulePage, contactPage],
};

export default weddingModernDraft;