begin;

-- =========================================================
-- Ko-Host Connect
-- Private consumer mailbox foundation
-- =========================================================
--
-- Each Connect request receives one temporary mailbox.
--
-- Consumer access:
--   /mailbox/[10-character mailbox code]
--   + separate 6-digit PIN
--
-- IMPORTANT:
-- - The raw PIN is never stored.
-- - Only its SHA-256 hash is stored.
-- - Mailboxes expire 12 days after creation.
-- - Public consumers do not receive direct database access.
-- - Mailbox access will happen through validated server APIs.
-- =========================================================


-- =========================================================
-- Mailboxes
-- =========================================================

create table if not exists public.connect_mailboxes (
  id uuid primary key default gen_random_uuid(),

  request_id uuid not null
    references public.connect_requests(id)
    on delete cascade,

  -- Public mailbox identifier used in:
  -- /mailbox/[mailbox_code]
  --
  -- Generated by the server.
  -- V1 format: exactly 10 alphanumeric characters.
  mailbox_code text not null unique
    check (
      mailbox_code ~ '^[A-Za-z0-9]{10}$'
    ),

  -- SHA-256 hash of the consumer's 6-digit PIN.
  -- The actual PIN is returned once during mailbox creation
  -- and may be emailed to the consumer, but is never stored.
  pin_hash text not null
    check (
      pin_hash ~ '^[a-f0-9]{64}$'
    ),

  status text not null default 'active'
    check (
      status in (
        'active',
        'expired',
        'closed'
      )
    ),

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now(),

  -- Mailbox lifetime is 12 days.
  expires_at timestamptz not null
    default (now() + interval '12 days'),

  -- One mailbox per consumer request.
  unique (request_id)
);


-- =========================================================
-- Indexes
-- =========================================================

create unique index if not exists idx_connect_mailboxes_code
  on public.connect_mailboxes(mailbox_code);

create unique index if not exists idx_connect_mailboxes_request
  on public.connect_mailboxes(request_id);

create index if not exists idx_connect_mailboxes_status
  on public.connect_mailboxes(status);

create index if not exists idx_connect_mailboxes_expires
  on public.connect_mailboxes(expires_at);


-- =========================================================
-- Row Level Security
-- =========================================================
--
-- No public policies are intentionally created here.
--
-- Consumers will authenticate to a mailbox through a
-- Ko-Host server API using mailbox_code + PIN.
--
-- Provider access will later be granted through the
-- Connect matching/thread system.
--
-- getSupabaseAdmin() bypasses RLS for trusted server-side
-- operations.
-- =========================================================

alter table public.connect_mailboxes
  enable row level security;


commit;