begin;

-- =========================================================
-- Ko-Host Connect
-- Consumer request foundation
-- =========================================================

create table if not exists public.connect_requests (
  id uuid primary key default gen_random_uuid(),

  -- Public-facing identifier.
  -- Generated by the server when the request is created.
  request_code text not null unique,

  -- Flat Ko-Host Connect service list value.
  service text not null,

  -- Consumer location used for provider matching.
  zip_code text not null,

  -- Date the consumer would like the service performed.
  -- Null allows "flexible / not sure yet" later without
  -- requiring a schema change.
  service_needed_date date,

  -- Consumer's description of the work needed.
  details text not null,

  -- Optional email used ONLY by Ko-Host for confirmations
  -- and mailbox-response notifications.
  -- This must never be exposed to providers.
  notification_email text,

  status text not null default 'open'
    check (
      status in (
        'open',
        'fulfilled',
        'cancelled',
        'expired'
      )
    ),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Request expiration is intentionally separate from
  -- mailbox expiration.
  expires_at timestamptz
);

-- Fast lookup by public request code.
create unique index if not exists idx_connect_requests_request_code
  on public.connect_requests(request_code);

-- Provider matching/filtering indexes.
create index if not exists idx_connect_requests_service
  on public.connect_requests(service);

create index if not exists idx_connect_requests_zip
  on public.connect_requests(zip_code);

create index if not exists idx_connect_requests_service_zip
  on public.connect_requests(service, zip_code);

create index if not exists idx_connect_requests_status
  on public.connect_requests(status);

create index if not exists idx_connect_requests_created
  on public.connect_requests(created_at desc);


-- =========================================================
-- Request photos
-- Up to 5 will be enforced by the server API.
-- =========================================================

create table if not exists public.connect_request_photos (
  id uuid primary key default gen_random_uuid(),

  request_id uuid not null
    references public.connect_requests(id)
    on delete cascade,

  storage_path text not null,

  original_file_name text,

  mime_type text,

  file_size_bytes bigint,

  sort_order integer not null default 0,

  created_at timestamptz not null default now(),

  unique (request_id, storage_path)
);

create index if not exists idx_connect_request_photos_request
  on public.connect_request_photos(request_id, sort_order);


-- =========================================================
-- Row Level Security
-- =========================================================
--
-- Public consumers do NOT receive direct database access.
--
-- Request creation will happen through a validated Ko-Host
-- server API using getSupabaseAdmin().
--
-- Provider access will later be granted through the
-- connect_request_matches system rather than making
-- connect_requests publicly readable.
-- =========================================================

alter table public.connect_requests
  enable row level security;

alter table public.connect_request_photos
  enable row level security;


-- =========================================================
-- Private request-photo storage
-- =========================================================

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'connect-request-images',
  'connect-request-images',
  false,
  5242880,
  array[
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;


-- =========================================================
-- Ko-Host Connect V1 service catalog
-- =========================================================
--
-- Keeping this as its own table means services can later
-- be added, removed, renamed, reordered, or disabled
-- without changing the Templates registry.
-- =========================================================

create table if not exists public.connect_services (
  id uuid primary key default gen_random_uuid(),

  slug text not null unique,
  name text not null unique,

  active boolean not null default true,
  sort_order integer not null default 0,

  created_at timestamptz not null default now()
);

alter table public.connect_services
  enable row level security;

-- Service names are not private.
drop policy if exists "connect_services_public_read"
  on public.connect_services;

create policy "connect_services_public_read"
on public.connect_services
for select
to public
using (active = true);


-- =========================================================
-- Initial flat service list
-- =========================================================

insert into public.connect_services (
  slug,
  name,
  sort_order
)
values
  ('lawn-care', 'Lawn Care', 10),
  ('house-cleaning', 'House Cleaning', 20),
  ('handyman', 'Handyman', 30),
  ('plumbing', 'Plumbing', 40),
  ('electrical', 'Electrical', 50),
  ('auto-repair', 'Auto Repair', 60),
  ('dog-walking', 'Dog Walking', 70),
  ('moving', 'Moving', 80),
  ('landscaping', 'Landscaping', 90),
  ('tree-service', 'Tree Service', 100),
  ('pressure-washing', 'Pressure Washing', 110),
  ('junk-removal', 'Junk Removal', 120),
  ('painting', 'Painting', 130),
  ('roofing', 'Roofing', 140),
  ('hvac', 'HVAC', 150),
  ('appliance-repair', 'Appliance Repair', 160),
  ('pest-control', 'Pest Control', 170),
  ('carpet-cleaning', 'Carpet Cleaning', 180),
  ('mobile-detailing', 'Mobile Detailing', 190),
  ('towing', 'Towing', 200),
  ('pet-sitting', 'Pet Sitting', 210),
  ('pet-grooming', 'Pet Grooming', 220),
  ('furniture-assembly', 'Furniture Assembly', 230),
  ('home-organization', 'Home Organization', 240),
  ('snow-removal', 'Snow Removal', 250),
  ('photography', 'Photography', 260),
  ('computer-repair', 'Computer Repair', 270),
  ('tutoring', 'Tutoring', 280)
on conflict (slug) do nothing;

commit;