export const ICON_TAGS: Record<string, string[]> = {
  "circle-one": ["one", "1", "number", "step", "circle"],
  "circle-two": ["two", "2", "number", "step", "circle"],
  "circle-three": ["three", "3", "number", "step", "circle"],
  "circle-four": ["four", "4", "number", "step", "circle"],
  "circle-five": ["five", "5", "number", "step", "circle"],
  "circle-six": ["six", "6", "number", "step", "circle"],
  "circle-seven": ["seven", "7", "number", "step", "circle"],
  "circle-eight": ["eight", "8", "number", "step", "circle"],
  "circle-nine": ["nine", "9", "number", "step", "circle"],
  "circle-ten": ["ten", "10", "number", "step", "circle"],

  "arrow-up-thick": ["arrow", "up", "direction", "navigation"],
  "arrow-down-thick": ["arrow", "down", "direction", "navigation"],
  "arrow-left-thick": ["arrow", "left", "direction", "navigation"],
  "arrow-right-thick": ["arrow", "right", "direction", "navigation"],
  "arrow-up-thin": ["arrow", "up", "direction", "navigation"],
  "arrow-down-thin": ["arrow", "down", "direction", "navigation"],
  "arrow-left-thin": ["arrow", "left", "direction", "navigation"],
  "arrow-right-thin": ["arrow", "right", "direction", "navigation"],
  "arrow-rotate": ["arrow", "rotate", "refresh", "reload", "repeat"],

  "chevron-left": ["chevron", "left", "previous", "back"],
  "chevron-right": ["chevron", "right", "next", "forward"],

  "add-plus": ["add", "plus", "new", "create"],
  "subtract-minus": ["subtract", "minus", "remove"],
  "information-circle": ["info", "information", "help"],
  "exclamation-round": ["alert", "warning", "important", "exclamation"],
  "question-mark-circle": ["question", "help", "faq"],
  "question-mark": ["question", "help", "faq"],
  "caution-circle": ["caution", "warning", "alert"],

  "paper-airplane": ["send", "message", "airplane", "paper"],
  "graduate-cap": ["school", "education", "graduate", "college"],
  "open-book": ["book", "read", "learn", "education"],
  "open-book-empty": ["book", "read", "learn", "education"],
  "closed-book": ["book", "read", "learn", "education"],

  "dog-paw": ["dog", "pet", "animal", "paw"],
  "dinosaur-rex": ["dinosaur", "rex", "kids", "animal"],
  "city": ["city", "building", "urban"],
  "house": ["house", "home", "property"],
  "gym-dumbbell": ["gym", "fitness", "workout", "exercise"],

  "download": ["download", "save"],
  "external-link": ["external", "link", "open"],
  "furniture-couch": ["furniture", "couch", "sofa", "junk"],
  "refrigerator": ["fridge", "refrigerator", "appliance", "junk"],
  "trash-can-waste": ["trash", "waste", "garbage", "junk"],
  "box-junk": ["box", "junk", "moving", "storage"],
  "truck-haul": ["truck", "haul", "moving", "junk", "delivery"],

  "stars-five": ["stars", "rating", "review", "quality"],
  star: ["star", "favorite", "rating"],
  heart: ["heart", "love", "favorite"],
  "heart-outline": ["heart", "love", "favorite"],
  circle: ["circle", "shape"],
  "open-circle": ["circle", "shape", "outline"],
  "circle-target": ["target", "goal", "circle"],

  "wellness-recovery": ["wellness", "health", "recovery"],
  nutrition: ["nutrition", "food", "health"],
  balloon: ["balloon", "party", "birthday", "celebration"],
  "plant-root": ["plant", "root", "garden", "nature"],
  trees: ["tree", "trees", "nature", "outdoor"],

  "dinner-cap": ["dinner", "food", "restaurant"],
  "formal-shirt": ["shirt", "formal", "clothes"],
  "formal-dress": ["dress", "formal", "clothes"],
  "contractor-worker": ["contractor", "worker", "construction"],
  hanger: ["hanger", "clothes", "fashion"],

  "stock-chart-up": ["chart", "stock", "up", "growth"],
  "stock-chart-down": ["chart", "stock", "down", "decline"],
  "party-confetti": ["party", "confetti", "celebration"],
  "megaphone-speaker": ["megaphone", "speaker", "announcement"],

  "lock-locked": ["lock", "locked", "secure", "private"],
  lock_unlock: ["unlock", "unlocked", "open"],
  "gift-box": ["gift", "present", "registry"],
  "folder-hierarchy": ["folder", "files", "hierarchy"],
  "export-share": ["export", "share"],
  "download-folder": ["download", "folder", "files"],
  tools: ["tools", "settings", "repair"],

  flag: ["flag", "marker", "country"],
  "fork-knife-plate": ["food", "plate", "restaurant", "dinner"],
  "glass-drink": ["drink", "glass", "beverage"],
  headphones: ["headphones", "audio", "music"],
  "headset-support": ["support", "help", "headset"],
  recycle: ["recycle", "green", "trash", "junk"],

  "champagne-flutes": ["champagne", "toast", "wedding", "celebration"],
  "birthday-cake": ["birthday", "cake", "party"],
  baby: ["baby", "shower", "child"],
  "music-note": ["music", "note", "song"],
  "music-note-treble-clef": ["music", "note", "song"],
  "notebook-pen": ["notebook", "pen", "write", "notes"],

  "play-triangle-solid": ["play", "video", "media"],
  "play-triangle-circle": ["play", "video", "media"],
  "pause-circle": ["pause", "video", "media"],
  eject: ["eject", "media"],

  "pin-tac": ["pin", "location", "marker"],
  "power-on": ["power", "on", "start"],
  trophy: ["trophy", "winner", "award"],
  "medal-check": ["medal", "award", "winner"],

  "credit-card": ["credit", "card", "payment"],
  "card-spade": ["card", "spade", "game"],
  "card-heart": ["card", "heart", "game"],
  "card-club": ["card", "club", "game"],
  "card-diamond": ["card", "diamond", "game"],

  "magnifying-glass": ["search", "find", "lookup"],
  "magnifying-glass-zoom-in": ["search", "zoom", "in"],
  "magnifying-glass-zoom-out": ["search", "zoom", "out"],

  clock: ["clock", "time", "schedule"],
  "clock-outline": ["clock", "time", "schedule"],
  "hour-glass-empty": ["hourglass", "time", "countdown"],
  "hour-glass-half": ["hourglass", "time", "countdown"],
  "hour-glass-full": ["hourglass", "time", "countdown"],

  "cross-cancel": ["cancel", "close", "x"],
  "ban-sign": ["ban", "no", "blocked"],
  "settings-gears": ["settings", "gear", "configure"],
  "tag-price": ["tag", "price", "sale"],
  "dollar-sign": ["dollar", "money", "payment"],
  "dollar-sign-circle": ["dollar", "money", "payment"],

  check: ["check", "done", "complete"],
  "check-square": ["check", "done", "complete"],
  "check-circle": ["check", "done", "complete"],
  "check-circle-solid": ["check", "done", "complete"],

  envelope: ["email", "mail", "message"],
  person: ["person", "user", "profile"],
  people: ["people", "users", "group"],
  "people-group": ["people", "users", "group"],
  camera: ["camera", "photo", "image"],
  calendar: ["calendar", "date", "schedule"],
  "calendar-full": ["calendar", "date", "schedule"],

  phone: ["phone", "call", "contact"],
  "shopping-cart": ["cart", "shopping", "checkout"],
  "location-pin": ["location", "pin", "map"],
  "location-pin-outline": ["location", "pin", "map"],
  "location-pin-alt": ["location", "pin", "map"],
  "video-camera": ["video", "camera", "record"],
  "training-presentation": ["training", "presentation", "learn"],

  "thumbs-up-outline": ["thumbs", "like", "yes"],
  "thumbs-up-solid": ["thumbs", "like", "yes"],
  "thumbs-down-outline": ["thumbs", "dislike", "no"],
  "thumbs-down-solid": ["thumbs", "dislike", "no"],

  "fire-flame": ["fire", "flame", "hot"],
  "photo-placeholder": ["photo", "image", "placeholder"],
};